---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---






<!--html_preserve--><div id="hukcbrzofz" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#hukcbrzofz .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hukcbrzofz .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hukcbrzofz .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hukcbrzofz .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hukcbrzofz .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hukcbrzofz .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hukcbrzofz .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hukcbrzofz .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hukcbrzofz .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hukcbrzofz .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hukcbrzofz .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hukcbrzofz .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hukcbrzofz .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hukcbrzofz .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hukcbrzofz .gt_from_md > :first-child {
  margin-top: 0;
}

#hukcbrzofz .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hukcbrzofz .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hukcbrzofz .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hukcbrzofz .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hukcbrzofz .gt_row_group_first td {
  border-top-width: 2px;
}

#hukcbrzofz .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hukcbrzofz .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hukcbrzofz .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hukcbrzofz .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hukcbrzofz .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hukcbrzofz .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hukcbrzofz .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hukcbrzofz .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hukcbrzofz .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hukcbrzofz .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hukcbrzofz .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hukcbrzofz .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hukcbrzofz .gt_left {
  text-align: left;
}

#hukcbrzofz .gt_center {
  text-align: center;
}

#hukcbrzofz .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hukcbrzofz .gt_font_normal {
  font-weight: normal;
}

#hukcbrzofz .gt_font_bold {
  font-weight: bold;
}

#hukcbrzofz .gt_font_italic {
  font-style: italic;
}

#hukcbrzofz .gt_super {
  font-size: 65%;
}

#hukcbrzofz .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#hukcbrzofz .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hukcbrzofz .gt_indent_1 {
  text-indent: 5px;
}

#hukcbrzofz .gt_indent_2 {
  text-indent: 10px;
}

#hukcbrzofz .gt_indent_3 {
  text-indent: 15px;
}

#hukcbrzofz .gt_indent_4 {
  text-indent: 20px;
}

#hukcbrzofz .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="isoyear">isoyear</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="date_min">date_min</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="date_max">date_max</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="consultations_n">consultations_n</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="isoyear" class="gt_row gt_right">2006</td>
<td headers="date_min" class="gt_row gt_right">2006-01-02</td>
<td headers="date_max" class="gt_row gt_right">2006-12-31</td>
<td headers="consultations_n" class="gt_row gt_right">19739344</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2007</td>
<td headers="date_min" class="gt_row gt_right">2007-01-01</td>
<td headers="date_max" class="gt_row gt_right">2007-12-30</td>
<td headers="consultations_n" class="gt_row gt_right">20583980</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2008</td>
<td headers="date_min" class="gt_row gt_right">2007-12-31</td>
<td headers="date_max" class="gt_row gt_right">2008-12-28</td>
<td headers="consultations_n" class="gt_row gt_right">21798361</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2009</td>
<td headers="date_min" class="gt_row gt_right">2008-12-29</td>
<td headers="date_max" class="gt_row gt_right">2010-01-03</td>
<td headers="consultations_n" class="gt_row gt_right">23771522</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2010</td>
<td headers="date_min" class="gt_row gt_right">2010-01-04</td>
<td headers="date_max" class="gt_row gt_right">2011-01-02</td>
<td headers="consultations_n" class="gt_row gt_right">23987847</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2011</td>
<td headers="date_min" class="gt_row gt_right">2011-01-03</td>
<td headers="date_max" class="gt_row gt_right">2012-01-01</td>
<td headers="consultations_n" class="gt_row gt_right">24933553</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2012</td>
<td headers="date_min" class="gt_row gt_right">2012-01-02</td>
<td headers="date_max" class="gt_row gt_right">2012-12-30</td>
<td headers="consultations_n" class="gt_row gt_right">24624010</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2013</td>
<td headers="date_min" class="gt_row gt_right">2012-12-31</td>
<td headers="date_max" class="gt_row gt_right">2013-12-29</td>
<td headers="consultations_n" class="gt_row gt_right">23168876</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2014</td>
<td headers="date_min" class="gt_row gt_right">2013-12-30</td>
<td headers="date_max" class="gt_row gt_right">2014-12-28</td>
<td headers="consultations_n" class="gt_row gt_right">23492814</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2015</td>
<td headers="date_min" class="gt_row gt_right">2014-12-29</td>
<td headers="date_max" class="gt_row gt_right">2016-01-03</td>
<td headers="consultations_n" class="gt_row gt_right">24256036</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2016</td>
<td headers="date_min" class="gt_row gt_right">2016-01-04</td>
<td headers="date_max" class="gt_row gt_right">2017-01-01</td>
<td headers="consultations_n" class="gt_row gt_right">24657816</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2017</td>
<td headers="date_min" class="gt_row gt_right">2017-01-02</td>
<td headers="date_max" class="gt_row gt_right">2017-12-31</td>
<td headers="consultations_n" class="gt_row gt_right">24385641</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2018</td>
<td headers="date_min" class="gt_row gt_right">2018-01-01</td>
<td headers="date_max" class="gt_row gt_right">2018-12-30</td>
<td headers="consultations_n" class="gt_row gt_right">23369284</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2019</td>
<td headers="date_min" class="gt_row gt_right">2018-12-31</td>
<td headers="date_max" class="gt_row gt_right">2019-12-29</td>
<td headers="consultations_n" class="gt_row gt_right">22975228</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2020</td>
<td headers="date_min" class="gt_row gt_right">2019-12-30</td>
<td headers="date_max" class="gt_row gt_right">2021-01-03</td>
<td headers="consultations_n" class="gt_row gt_right">27066292</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2021</td>
<td headers="date_min" class="gt_row gt_right">2021-01-04</td>
<td headers="date_max" class="gt_row gt_right">2022-01-02</td>
<td headers="consultations_n" class="gt_row gt_right">28880933</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2022</td>
<td headers="date_min" class="gt_row gt_right">2022-01-03</td>
<td headers="date_max" class="gt_row gt_right">2023-01-01</td>
<td headers="consultations_n" class="gt_row gt_right">27048916</td></tr>
    <tr><td headers="isoyear" class="gt_row gt_right">2023</td>
<td headers="date_min" class="gt_row gt_right">2023-01-02</td>
<td headers="date_max" class="gt_row gt_right">2023-03-16</td>
<td headers="consultations_n" class="gt_row gt_right">5128520</td></tr>
  </tbody>
  
  
</table>
</div><!--/html_preserve-->





