icpc2 <- rbindlist(list(
  # Single
  data.table("A02", "a02", "Chills", "Symptoms/Complaints", "General and unspecified", "Frysninger", "Symptomer", "Allment og uspesifisert"),
  data.table("A03", "a03", "Fever", "Symptoms/Complaints", "General and unspecified", "Feber", "Symptomer", "Allment og uspesifisert"),
  data.table("A05", "a05", "Feeling ill", "Symptoms/Complaints", "General and unspecified", "Sykdomsfølelse", "Symptomer", "Allment og uspesifisert"),
  data.table("A71", "a71", "Measles", "Infections", "General and unspecified", "Meslinger", "Infeksjoner", "Allment og uspesifisert"),
  data.table("A72", "a72", "Chickenpox", "Infections", "General and unspecified", "Vannkopper", "Infeksjoner", "Allment og uspesifisert"),
  data.table("A73", "a73", "Malaria", "Infections", "General and unspecified", "Malaria", "Infeksjoner", "Allment og uspesifisert"),
  data.table("A74", "a74", "Rubella", "Infections", "General and unspecified", "Røde hunder", "Infeksjoner", "Allment og uspesifisert"),
  data.table("A75", "a75", "Infectious mononucleosis", "General and unspecified", "Infections", "Mononukleose", "Infeksjoner", "Allment og uspesifisert"),
  data.table("A76", "a76", "Viral exanthem other", "General and unspecified", "Infections", "Virussykdom med utslett IKA", "Infeksjoner", "Allment og uspesifisert"),
  data.table("A77", "a77", "Viral disease other/NOS", "General and unspecified", "Infections", "Virussykdom IKA", "Infeksjoner", "Allment og uspesifisert"),
  data.table("A78", "a78", "Infectious disease other/NOS", "General and unspecified", "Infections", "Infeksjonssykdom IKA", "Infeksjoner", "Allment og uspesifisert"),
  data.table("B02", "b02", "Lymph gland(s) enlarged/painful", "Symptoms/Complaints", "Blood, blood forming organs, and immune mechanism", "Lymfeknuter forstørrede/smertefulle", "Symptomer", "Blod, bloddannende organer og immunsystemet"),
  data.table("B70", "b70", "Lymphadenitis acute", "Infections", "Blood, blood forming organs, and immune mechanism", "Lymfadenitt akutt", "Infeksjoner", "Blod, bloddannende organer og immunsystemet"),
  data.table("B71", "b71", "lymphadenitis non-specific", "Infections", "Blood, blood forming organs, and immune mechanism", "Lymfadenitt kronisk/uspesifikk", "Infeksjoner", "Blod, bloddannende organer og immunsystemet"),
  data.table("D01", "d01", "Abdominal pain/cramps general", "Symptoms/Complaints", "Digestive", "Abdominalsmerte/krampe generell", "Symptomer", "Fordøyelsessystemet"),
  data.table("D02", "d02", "Abdominal pain epigastric", "Symptoms/Complaints", "Digestive", "Abdominalsmerte epigastriet", "Symptomer", "Fordøyelsessystemet"),
  data.table("D06", "d06", "Abdominal pain localized other", "Symptoms/Complaints", "Digestive", "Abdonimalsmerte lokalisert IKA", "Symptomer", "Fordøyelsessystemet"),
  data.table("D08", "d08", "Flatulence/gas/belching", "Symptoms/Complaints", "Digestive", "Flatulens/oppblåsthet/raping", "Symptomer", "Fordøyelsessystemet"),
  data.table("D09", "d09", "Nausea", "Symptoms/Complaints", "Digestive", "Kvalme", "Symptomer", "Fordøyelsessystemet"),
  data.table("D10", "d10", "Vomiting", "Symptoms/Complaints", "Digestive", "Oppkast/brekninger", "Symptomer", "Fordøyelsessystemet"),
  data.table("D11", "d11", "Diarrhea", "Symptoms/Complaints", "Digestive", "Diaré", "Symptomer", "Fordøyelsessystemet"),
  data.table("D14", "d14", "Hematemesis/vomiting blood", "Symptoms/Complaints", "Digestive", "Oppkast med blod/hematemese", "Symptomer", "Fordøyelsessystemet"),
  data.table("D18", "d18", "Change feces/bowel movements", "Symptoms/Complaints", "Digestive", "Endring i avføring/avføringsvane", "Symptomer", "Fordøyelsessystemet"),
  data.table("D25", "d25", "Abdominal distension", "Symptoms/Complaints", "Digestive", "Utspilt abdomen", "Symptomer", "Fordøyelsessystemet"),
  data.table("D29", "d29", "Digestive symptom/complaint other", "Symptoms/Complaints", "Digestive", "Fordøyelsesyst symptomer/plager IKA", "Symptomer", "Fordøyelsessystemet"),
  data.table("D70", "d70", "Gastrointestinal infection", "Infections", "Digestive", "Tarminfeksjon", "Infeksjoner", "Fordøyelsessystemet"),
  data.table("D73", "d73", "Gastroenteritis presumed infection", "Infections", "Digestive", "Gastroenteritt antatt infeksiøs", "Infeksjoner", "Fordøyelsessystemet"),
  data.table("D87", "d87", "Stomach function disorder", "Other diagnoses", "Digestive", "Funksjonelle plager magesekk", "Annet", "Fordøyelsessystemet"),
  data.table("D99", "d99", "Disease digestive system, other", "Other diagnoses", "Digestive", "Sykdom i fordøyelsessystemet IKA", "Annet", "Fordøyelsessystemet"),
  data.table("F70", "f70", "Conjunctivitis infectious", "Infections", "Eye", "Infeksiøs konjunktivitt", "Infeksjoner", "Øye"),
  data.table("F73", "f73", "Eye infection/inflammation other", "Infections", "Eye", "Øye infeksjon/betennelse IKA", "Infeksjoner", "Øye"),
  data.table("H01", "h01", "Ear pain/earache", "Symptoms/Complaints", "Ear", "Øresmerte/øreverk", "Symptomer", "Øre"),
  data.table("H04", "h04", "Ear discharge", "Symptoms/Complaints", "Ear", "Øreflod/sekresjon", "Symptomer", "Øre"),
  data.table("H13", "h13", "Plugged feeling ear", "Symptoms/Complaints", "Ear", "Øreplugg/øretetthet", "Symptomer", "Øre"),
  data.table("H29", "h29", "Ear symptom/complaint other", "Symptoms/Complaints", "Ear", "Øre symptomer/plager IKA", "Symptomer", "Øre"),
  data.table("H71", "h71", "Acute otitis media/myringitis", "Infections", "Ear", "Mellomørebetennelse akutt", "Symptomer", "Øre"),
  data.table("H77", "h77", "Perforation ear drum", "Injuries", "Ear", "Perforert trommehinne IKA", "Skader", "Øre"),
  data.table("R01", "r01", "Pain respiratory system", "Symptoms/Complaints", "Respiratory", "Smerte luftveier", "Symptomer", "Luftveier"),
  data.table("R02", "r02", "Shortness of breat/dyspnea", "Symptoms/Complaints", "Respiratory", "Kortpustethet/dyspné", "Symptomer", "Luftveier"),
  data.table("R03", "r03", "Wheezing", "Symptoms/Complaints", "Respiratory", "Piping i brystet", "Symptomer", "Luftveier"),
  data.table("R04", "r04", "Breathing problem, other", "Symptoms/Complaints", "Respiratory", "Pusteproblem IKA", "Symptomer", "Luftveier"),
  data.table("R05", "r05", "Cough", "Symptoms/Complaints", "Respiratory", "Hoste", "Symptomer", "Luftveier"),
  data.table("R06", "r06", "Nose bleed/epistaxis", "Symptoms/Complaints", "Respiratory", "Neseblødning", "Symptomer", "Luftveier"),
  data.table("R07", "r07", "Sneezing/nasal congestion", "Symptoms/Complaints", "Respiratory", "Nysing/tetthet i nese", "Symptomer", "Luftveier"),
  data.table("R08", "r08", "Nose symptom/complaint other", "Symptoms/Complaints", "Respiratory", "Nese symptomer/plager IKA", "Symptomer", "Luftveier"),
  data.table("R09", "r09", "Sinus symptom/complaint", "Symptoms/Complaints", "Respiratory", "Bihule symptomer/plager IKA", "Symptomer", "Luftveier"),
  data.table("R21", "r21", "Throat symptom/complaint", "Symptoms/Complaints", "Respiratory", "Hals symptomer/plager", "Symptomer", "Luftveier"),
  data.table("R24", "r24", "Hemoptysis", "Symptoms/Complaints", "Respiratory", "Blodig oppspytt/hemoptyse", "Symptomer", "Luftveier"),
  data.table("R25", "r25", "Sputum/phlegm abnormal", "Symptoms/Complaints", "Respiratory", "Unormalt oppspytt/ekspektorat", "Symptomer", "Luftveier"),
  data.table(list(c("R27", "R270000")), "r27", "Fear of respiratory disease, other", "Symptoms/Complaints", "Respiratory", "Engstelig for sykdom luftveier IKA", "Symptomer", "Luftveier"),
  data.table("R29", "r29", "Respiratory symptom/complaint other", "Symptoms/Complaints", "Respiratory", "Luftveier symptomer/plager IKA", "Symptomer", "Luftveier"),
  data.table("R33", "r33", "Respiratory microbiological/immunological test", "Process codes", "Respiratory", "Luftveier mikrobiologisk/immunologisk prøve", "Prosesskoder", "Luftveier"),
  data.table("R71", "r71", "Whooping cough", "Infections", "Respiratory", "Kikhoste", "Infeksjoner", "Luftveier"),
  data.table("R72", "r72", "Strep throat", "Infections", "Respiratory", "Streptokokkhals", "Infeksjoner", "Luftveier"),
  data.table("R74", "r74", "Upper respiratory infection acute", "Infections", "Respiratory", "Akutt øvre luftveisinfeksjon", "Infeksjoner", "Luftveier"),
  data.table("R75", "r75", "Sinusitis acute/chronic", "Infections", "Respiratory", "Bihulebetennelse", "Infeksjoner", "Luftveier"),
  data.table("R76", "r76", "Tonsillitis acute", "Infections", "Respiratory", "Akutt tonsillitt", "Infeksjoner", "Luftveier"),
  data.table("R77", "r77", "Laryngitis/tracheitis acute", "Infections", "Respiratory", "Akutt laryngitt/trakeitt", "Infeksjoner", "Luftveier"),
  data.table("R78", "r78", "Acute bronchitis/bronchiolitis", "Infections", "Respiratory", "Akutt bronkitt/bronkiolitt", "Infeksjoner", "Luftveier"),
  data.table("R79", "r79", "Chronic bronchitis", "Infections", "Respiratory", "Kronisk bronkitt", "Infeksjoner", "Luftveier"),
  data.table("R80", "r80", "Influenza", "Infections", "Respiratory", "Influensa", "Infeksjoner", "Luftveier"),
  data.table("R81", "r81", "Pneumonia", "Infections", "Respiratory", "Lungebetennelse", "Infeksjoner", "Luftveier"),
  data.table("R82", "r82", "Pleurisy/pleural effusion", "Infections", "Respiratory", "Pleuritt IKA", "Infeksjoner", "Luftveier"),
  data.table("R83", "r83", "Respiratory infection other", "Infections", "Respiratory", "Luftveisinfeksjon IKA", "Infeksjoner", "Luftveier"),
  data.table("R95", "r95", "Chronic obstructive pulmonary disorder", "Other diagnoses", "Respiratory", "Kronisk obstruktiv lungesykdom", "Annet", "Luftveier"),
  data.table("R96", "r96", "Asthma", "Other diagnoses", "Respiratory", "Astma", "Annet", "Luftveier"),
  data.table("R99", "r99", "Respiratory disease other", "Other diagnoses", "Respiratory", "Luftveissykdom IKA", "Annet", "Luftveier"),
  data.table(list(c("R991", "R9910000")), "r991", "COVID-19 (Probable/Suspected)", "Infections", "Respiratory", "Covid-19 (sannsynlig/mistenkt)", "Infeksjoner", "Luftveier"),
  data.table(list(c("R992", "R9920000")), "r992", "COVID-19 (Confirmed)", "Infections", "Respiratory", "Covid-19 (bekreftet)", "Infeksjoner", "Luftveier"),
  data.table("S06", "s06", "Rash localized", "Symptoms/Complaints", "Skin", "Lokalisert utslett hud", "Symptomer", "Hud"),
  data.table("S07", "s07", "Rash generalized", "Symptoms/Complaints", "Skin", "Utbredte utslett hud", "Symptomer", "Hud"),
  data.table("S10", "s10", "Boil/carbuncle", "Infections", "Skin", "Abscess/furunkel", "Infeksjoner", "Hud"),
  data.table("S12", "s12", "Insect bite/sting", "Injuries", "Skin", "Insektstikk/bitt", "Skader", "Hud"),
  data.table("S17", "s17", "Abrasion/scratch/blister", "Injuries", "Skin", "Skrubbsår/blemmer", "Skader", "Hud"),
  data.table("S29", "s29", "Skin symptom/complaint other", "Symptoms/Complaints", "Skin", "Hud symptomer/plager IKA", "Symptomer", "Hud"),
  data.table("S70", "s70", "Herpes zoster", "Infections", "Skin", "Herpes zoster", "Infeksjoner", "Hud"),
  data.table("S71", "s71", "Herpes simplex", "Infections", "Skin", "Herpes simplex IKA", "Infeksjoner", "Hud"),
  data.table("S72", "s72", "Scabies/other acariasis", "Infections", "Skin", "Skabb/infestasjon midd", "Infeksjoner", "Hud"),
  data.table("S73", "s73", "Pediculosis/skin infestation other", "Infections", "Skin", "Infestasjon parasitt IKA", "Infeksjoner", "Hud"),
  data.table("S76", "s76", "Skin infection other", "Infections", "Skin", "Hudinfeksjon IKA", "Infeksjoner", "Hud"),
  data.table("S84", "s84", "Impetigo", "Infections", "Skin", "Brennkopper", "Infeksjoner", "Hud"),
  data.table("S95", "s95", "Molluscum contagiosum", "Infections", "Skin", "Molluscum contagiosum", "Infeksjoner", "Hud"),
  data.table("S99", "s99", "Skin disease, other", "Other diagnoses", "Skin", "Hud/underhud sykdom IKA", "Annet", "Hud"),
  # Combinations
  data.table(list(c("D11", "D70", "D73")), "gastroenteritis", "Gastroenteritis", "Combination", "Digestive", "Mage-tarminfeksjoner", "Kombinasjon", "Fordøyelsessystemet"),
  data.table(list(c(
    "R01",
    "R02",
    "R03",
    "R04",
    "R05",
    # "R06",
    "R07",
    "R08",
    "R09",
    "R21",
    "R24",
    "R25",
    "R27",
    "R270000",
    "R29",
    "R33",
    "R71",
    "R72",
    "R74",
    "R75",
    "R76",
    "R77",
    "R78",
    "R79",
    "R80",
    "R81",
    "R82",
    "R83",
    # "R95",
    # "R96",
    "R99",
    "R991",
    "R9910000",
    "R992",
    "R9920000"
  )), "respiratory", "Respiratory infections", "Combination", "Respiratory", "Luftveisinfeksjoner", "Kombinasjon", "Luftveier"),
  data.table(list(c("R991", "R9910000", "R992", "R9920000", "R33")), "covid19", "COVID-19", "Combination", "Respiratory", "Covid-19", "Kombinasjon", "Luftveier")
))
#setnames(icpc2, c("raw_code", "end_code", "description_en", "grouping_en"))
